# Generated by Django 3.2.3 on 2021-06-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_person_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_1',
            name='credit_card_number',
            field=models.CharField(db_index=True, max_length=90),
        ),
    ]
